# Generated by Django 4.0.5 on 2022-12-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_gamelog_performed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelog',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gamelog',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playerorder',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='playerorder',
            name='player',
        ),
        migrations.RemoveField(
            model_name='tile',
            name='game',
        ),
        migrations.RemoveField(
            model_name='token',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='token',
            name='where',
        ),
        migrations.RemoveField(
            model_name='message',
            name='game',
        ),
        migrations.RemoveField(
            model_name='users',
            name='currently_playing',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='GameLog',
        ),
        migrations.DeleteModel(
            name='PlayerOrder',
        ),
        migrations.DeleteModel(
            name='Tile',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
