# Generated by Django 4.0.5 on 2022-12-02 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='geo_lan',
            new_name='geo_lat',
        ),
    ]
