# Generated by Django 4.0.5 on 2022-12-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_gamelog_game_remove_gamelog_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_picture',
            field=models.TextField(null=True),
        ),
    ]
