# Generated by Django 4.0.5 on 2022-12-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_rename_geo_lan_post_geo_lat'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
